spring:
  application:
    name: MyConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kalyani-p-dev/Stock
          username: kalyani-p-dev
          clone-on-start: true
          default-label: main
          
server:
  port: 8888